# Generated by Django 5.2 on 2025-05-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intro",
            options={
                "verbose_name": "Portfolio Introduction",
                "verbose_name_plural": "Portfolio Introductions",
            },
        ),
        migrations.AddField(
            model_name="intro",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intro",
                to="myportfolio.register",
            ),
        ),
    ]
