# Generated by Django 5.2 on 2025-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0002_alter_intro_options_intro_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intro",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
