# Generated by Django 5.2 on 2025-06-05 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0003_alter_intro_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_email", models.EmailField(max_length=254, unique=True)),
                ("industry", models.CharField(max_length=50)),
                ("company_size", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="intro",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"],
                        message="Please upload a valid document file (PDF, DOC, or DOCX).",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="intro",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intro",
                to="myportfolio.register",
            ),
        ),
    ]
