# Generated by Django 5.2 on 2025-06-05 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0004_company_alter_intro_resume_alter_intro_user"),
        ("myportfolio", "XXXX_set_default_user"),
    ]

    operations = []
