# Generated by Django 5.2 on 2025-06-05 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0005_merge_20250605_1021"),
        ("myportfolio", "XXXX_merge"),
    ]

    operations = []
