# Generated by Django 5.1.8 on 2025-06-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_merge_0005_merge_20250605_1021_XXXX_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AlterField(
            model_name='intro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro', to='myportfolio.register'),
        ),
    ]
